default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>  # Use "localhost" instead of "postgres"
  username: <%= ENV.fetch("MINATO_DATABASE_USERNAME", "minato") %>
  password: <%= ENV.fetch("MINATO_DATABASE_PASSWORD", "minato") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: minato_development

test:
  <<: *default
  database: minato_test

production:
  primary: &primary_production
    <<: *default
    database: minato_production
    username: <%= ENV["MINATO_DATABASE_USERNAME"] %>
    password: <%= ENV["MINATO_DATABASE_PASSWORD"] %>
