default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("MINATO_DATABASE_USERNAME") %>
  password: <%= ENV.fetch("MINATO_DATABASE_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  primary:
    <<: *default
    database: minato_development
    migrations_paths: db/migrate

  queue:
    <<: *default
    database: minato_queue_development
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: minato_test
    migrations_paths: db/migrate

  queue:
    <<: *default
    database: minato_queue_test
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: minato_production
    host: <%= ENV.fetch("DB_HOST", "192.168.0.200") %>
    username: <%= ENV["MINATO_DATABASE_USERNAME"] %>
    password: <%= ENV["MINATO_DATABASE_PASSWORD"] %>
    migrations_paths: db/migrate

  queue:
    <<: *primary_production
    database: minato_queue_production
    migrations_paths: db/queue_migrate
